// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWMzcdK-xqSAqlsRAtYK6Zfn02_RydK0',
    appId: '1:779798219382:web:3f3d0281dfd3858ef4ed57',
    messagingSenderId: '779798219382',
    projectId: 'tecnm-chat-celaya',
    authDomain: 'tecnm-chat-celaya.firebaseapp.com',
    storageBucket: 'tecnm-chat-celaya.firebasestorage.app',
    measurementId: 'G-T2BCR06ZP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWwgboI8YiMJ4fnVG6kjw-C6kcU5bAuA',
    appId: '1:779798219382:android:069117105a82984af4ed57',
    messagingSenderId: '779798219382',
    projectId: 'tecnm-chat-celaya',
    storageBucket: 'tecnm-chat-celaya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWBTe3hWBDKGkspNUzyY4S1C_kNeEjlc',
    appId: '1:779798219382:ios:b51ca976cd492856f4ed57',
    messagingSenderId: '779798219382',
    projectId: 'tecnm-chat-celaya',
    storageBucket: 'tecnm-chat-celaya.firebasestorage.app',
    iosBundleId: 'com.tecnm.tecnmChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWBTe3hWBDKGkspNUzyY4S1C_kNeEjlc',
    appId: '1:779798219382:ios:b51ca976cd492856f4ed57',
    messagingSenderId: '779798219382',
    projectId: 'tecnm-chat-celaya',
    storageBucket: 'tecnm-chat-celaya.firebasestorage.app',
    iosBundleId: 'com.tecnm.tecnmChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgWMzcdK-xqSAqlsRAtYK6Zfn02_RydK0',
    appId: '1:779798219382:web:ce8e61ef6e9e77c0f4ed57',
    messagingSenderId: '779798219382',
    projectId: 'tecnm-chat-celaya',
    authDomain: 'tecnm-chat-celaya.firebaseapp.com',
    storageBucket: 'tecnm-chat-celaya.firebasestorage.app',
    measurementId: 'G-QQ1VZJNM1C',
  );
}
